### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by affo5** [Imprex-Development/orebfuscator#138]
How do I config it to work in my world? I figured out how to make it work but wanted to name my world SMP. I am using apex server hosting and not sure how to make it so it works on this world named SMP.

**Comment by Ingrim4** [comment]
```yml
version: 1
general:
  updateOnBlockDamage: true
  bypassNotification: true
  initialRadius: 1
  updateRadius: 2
  proximityHiderRunnerSize: 4
cache:
  enabled: true
  baseDirectory: 'orebfuscator_cache/'
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000‬
  maximumSize: 8192
  expireAfterAccess: 30000
  maximumTaskQueueSize: 32768
  protocolLibThreads: -1
world:
  - worlds:
      - world
      - <insert world name here> # <--- this is the part where you can register worlds to be obfuscated
    enabled: true
    hiddenBlocks:
      - emerald_ore
      - deepslate_emerald_ore
      - diamond_ore
      - deepslate_diamond_ore

...

```
