### ISSUE TITLE
Better Tutorial for orebfuscator.bypass.

### ISSUE THREAD

**Issue by Craftphips** [Imprex-Development/orebfuscator#193]
### Description

Hello,
i couldn't find a useful "tutorial" for the orebfuscator.bypass config. I have my own minecraft spigot server, but when I go to the spectator the anti x-ray activates, and my fps drop like shit. In the config.yml I can't find it and there is no command to do this. Can someone pls help me with this?

### Proposed Behaviour

Just a short text with pictures or a video that shows how to do this exact, so someone that doesn't know much about programing can do it.

**Comment by NgLoader** [comment]
``orebfuscator.bypass`` is a permission for your permission plugin to bypass orebfuscator.
When have FPS issues please read [common issues #users-experience-low-fps](https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#users-experience-low-fps)

When you don't use a permission plugin you can use the default [bukkit permission system](https://bukkit.fandom.com/wiki/Permissions.yml)

Here is a short example of a permissions.yml when using the default bukkit permission system
```yml
server.admin:
       description: Admin permissions for My Server.
       default: op
       children:
          orebfuscator.bypass: true
```
