### ISSUE TITLE
😍 Understanding how it works to disable all xrays sources test with advanced xray mod. [RESOLVED] 😍

### ISSUE THREAD

**Issue by comonier** [Imprex-Development/orebfuscator#263]
### Description

i decide use oreb because paper anti-xray not work for spawners or chests
i mean works againt xray mod from  https://www.curseforge.com/minecraft/mc-mods/advanced-xray/files
that mod permit user add blocks to be searched with colored borders
antixray of paper block ores only but not works with chests / spawners
i dont know how oreb can hide spawners from xray and it works i saw the xray from spawner just disapear on my front, but i test it on a player account and it really was hidded from me using mod to xray and find it . 

so i just edit config, seach for all spawners registered and add one line with sculk_sensor to do a test but it not works.

but i tried to manually add on config.yml in hiddenBlocks: `sculk_sensor`
**Just on proximity menu** because there is no spawner registered on any other place and it works**
![image](https://user-images.githubusercontent.com/19571541/213573585-a542be56-c99d-4085-8bab-10b9fdd15d21.png)

```java
      minecraft:spawner: {}
      minecraft:sculk_sensor: {}
```

and i gues it not support it because the sculk_sensor block was not hidded like spawner.

![image](https://user-images.githubusercontent.com/19571541/213572095-31ae6f47-c50b-4c4d-b897-882bcf8a5dea.png)

### Reproduction Steps

install froge/xray mod
https://www.curseforge.com/minecraft/mc-mods/advanced-xray/files
enter on any server
add sculk_sensor 
and done.

oreb works to hide spawners but not worked when i put sculk_sensor on list

### Expected Behaviour

well i expected oreb could hide any block, like did with spawners and chests but i guess it not work with sculk_sensor

![image](https://user-images.githubusercontent.com/19571541/213572741-e5e30aaa-ee0a-480c-b0d1-14f3d53a872f.png)

### Server Details

Current: git-Purpur-1895 (MC: 1.19.3)*

### Orebfuscator Version

5.3.2

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b606

**Comment by Ingrim4** [comment]
Just tested what you described with spigot 1.19.3 and everything worked as expected. Can't really reproduce your issue maybe you configured something wrong. Does the console have any warnings/errors related to OFC?

**Comment by comonier** [comment]
well am trying do a new test on paper with https://www.curseforge.com/minecraft/mc-mods/advanced-xray-fabric-edition
and the plugin not hide border of xray on spawner and chest cases
![image](https://user-images.githubusercontent.com/19571541/213753611-a3afd6d9-4c1d-471b-b619-48cd835b5311.png)
i guess it just stop to works. it works for you ?

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/213753779-70f1302e-0c1d-407d-900f-cfaae6ffc25c.png)

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/213754266-da4cb35e-bf61-4b25-82c0-d68cc9d3c946.png)

**Comment by comonier** [comment]
```yaml
version: 2
general:
  checkForUpdates: true
  updateOnBlockDamage: true
  bypassNotification: true
  ignoreSpectator: false
  updateRadius: 2
advanced:
  verbose: false
  useAsyncPacketListener: true
  maxMillisecondsPerTick: 10
  protocolLibThreads: -1
  obfuscationWorkerThreads: -1
  proximityHiderThreads: -1
cache:
  enabled: true
  baseDirectory: orebfuscator_cache
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000
  enableDiskCache: true
  maximumSize: 16384
  expireAfterAccess: 60000
  maximumTaskQueueSize: 32768
obfuscation:
  obfuscation-overworld:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - world
    hiddenBlocks:
    - minecraft:emerald_ore
    - minecraft:deepslate_emerald_ore
    - minecraft:diamond_ore
    - minecraft:deepslate_diamond_ore
    - minecraft:gold_ore
    - minecraft:deepslate_gold_ore
    - minecraft:raw_gold_block
    - minecraft:iron_ore
    - minecraft:deepslate_iron_ore
    - minecraft:raw_iron_block
    - minecraft:coal_ore
    - minecraft:deepslate_coal_ore
    - minecraft:lapis_ore
    - minecraft:deepslate_lapis_ore
    - minecraft:redstone_ore
    - minecraft:deepslate_redstone_ore
    - minecraft:copper_ore
    - minecraft:raw_copper_block
    - minecraft:deepslate_copper_ore
    - minecraft:stone
    - minecraft:deepslate
    - minecraft:chest
    - minecraft:ender_chest
    - minecraft:trapped_chest
    - minecraft:shulker_box
    - minecraft:white_shulker_box
    - minecraft:orange_shulker_box
    - minecraft:magenta_shulker_box
    - minecraft:light_blue_shulker_box
    - minecraft:yellow_shulker_box
    - minecraft:lime_shulker_box
    - minecraft:pink_shulker_box
    - minecraft:gray_shulker_box
    - minecraft:light_gray_shulker_box
    - minecraft:cyan_shulker_box
    - minecraft:purple_shulker_box
    - minecraft:blue_shulker_box
    - minecraft:brown_shulker_box
    - minecraft:green_shulker_box
    - minecraft:red_shulker_box
    - minecraft:black_shulker_box
    randomBlocks:
      minecraft:stone: 30
      minecraft:deepslate: 30
      minecraft:cave_air: 5
      minecraft:cobblestone: 1
      minecraft:diamond_ore: 25
      minecraft:emerald_ore: 10
      minecraft:gold_ore: 5
      minecraft:iron_ore: 5
      minecraft:copper_ore: 5
      minecraft:coal_ore: 5
      minecraft:lapis_ore: 5
      minecraft:redstone_ore: 5
      minecraft:mossy_cobblestone: 1
      minecraft:obsidian: 1
      minecraft:tnt: 1
  obfuscation-nether:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - world_nether
    hiddenBlocks:
    - minecraft:netherrack
    - minecraft:nether_quartz_ore
    - minecraft:chest
    - minecraft:ender_chest
    - minecraft:trapped_chest
    - minecraft:shulker_box
    - minecraft:white_shulker_box
    - minecraft:orange_shulker_box
    - minecraft:magenta_shulker_box
    - minecraft:light_blue_shulker_box
    - minecraft:yellow_shulker_box
    - minecraft:lime_shulker_box
    - minecraft:pink_shulker_box
    - minecraft:gray_shulker_box
    - minecraft:light_gray_shulker_box
    - minecraft:cyan_shulker_box
    - minecraft:purple_shulker_box
    - minecraft:blue_shulker_box
    - minecraft:brown_shulker_box
    - minecraft:green_shulker_box
    - minecraft:red_shulker_box
    - minecraft:black_shulker_box
    - minecraft:ancient_debris
    - minecraft:nether_gold_ore
    - minecraft:basalt
    - minecraft:soul_sand
    - minecraft:soul_soil
    randomBlocks:
      minecraft:netherrack: 4
      minecraft:nether_quartz_ore: 1
      minecraft:nether_gold_ore: 1
      minecraft:ancient_debris: 1
  obfuscation-end:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - world_the_end
    hiddenBlocks:
    - minecraft:chest
    - minecraft:ender_chest
    - minecraft:trapped_chest
    - minecraft:shulker_box
    - minecraft:white_shulker_box
    - minecraft:orange_shulker_box
    - minecraft:magenta_shulker_box
    - minecraft:light_blue_shulker_box
    - minecraft:yellow_shulker_box
    - minecraft:lime_shulker_box
    - minecraft:pink_shulker_box
    - minecraft:gray_shulker_box
    - minecraft:light_gray_shulker_box
    - minecraft:cyan_shulker_box
    - minecraft:purple_shulker_box
    - minecraft:blue_shulker_box
    - minecraft:brown_shulker_box
    - minecraft:green_shulker_box
    - minecraft:red_shulker_box
    - minecraft:black_shulker_box
    randomBlocks:
      minecraft:end_stone: 1
      minecraft:end_stone_bricks: 1
      minecraft:bedrock: 1
      minecraft:obsidian: 1
      minecraft:purpur_block: 1
proximity:
  proximity-overworld:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - world
    distance: 24
    useFastGazeCheck: false
    useBlockBelow: true
    hiddenBlocks:
      minecraft:mossy_cobblestone: {}
      minecraft:diamond_ore: {}
      minecraft:deepslate_diamond_ore: {}
      minecraft:emerald_ore: {}
      minecraft:deepslate_emerald_ore: {}
      minecraft:chest: {}
      minecraft:ender_chest: {}
      minecraft:trapped_chest: {}
      minecraft:anvil: {}
      minecraft:crafting_table: {}
      minecraft:dispenser: {}
      minecraft:enchanting_table: {}
      minecraft:furnace: {}
      minecraft:blast_furnace: {}
      minecraft:cartography_table: {}
      minecraft:fletching_table: {}
      minecraft:grindstone: {}
      minecraft:composter: {}
      minecraft:lectern: {}
      minecraft:loom: {}
      minecraft:smithing_table: {}
      minecraft:smoker: {}
      minecraft:stonecutter: {}
      minecraft:hopper: {}
      minecraft:spawner: {}
      minecraft:shulker_box: {}
      minecraft:white_shulker_box: {}
      minecraft:orange_shulker_box: {}
      minecraft:magenta_shulker_box: {}
      minecraft:light_blue_shulker_box: {}
      minecraft:yellow_shulker_box: {}
      minecraft:lime_shulker_box: {}
      minecraft:pink_shulker_box: {}
      minecraft:gray_shulker_box: {}
      minecraft:light_gray_shulker_box: {}
      minecraft:cyan_shulker_box: {}
      minecraft:purple_shulker_box: {}
      minecraft:blue_shulker_box: {}
      minecraft:brown_shulker_box: {}
      minecraft:green_shulker_box: {}
      minecraft:red_shulker_box: {}
      minecraft:black_shulker_box: {}
      minecraft:bee_nest: {}
      minecraft:beehive: {}
    randomBlocks:
      minecraft:stone: 1
  proximity-nether:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - world_nether
    distance: 24
    useFastGazeCheck: false
    useBlockBelow: true
    hiddenBlocks:
      minecraft:chest: {}
      minecraft:ender_chest: {}
      minecraft:trapped_chest: {}
      minecraft:anvil: {}
      minecraft:crafting_table: {}
      minecraft:dispenser: {}
      minecraft:enchanting_table: {}
      minecraft:furnace: {}
      minecraft:blast_furnace: {}
      minecraft:cartography_table: {}
      minecraft:fletching_table: {}
      minecraft:grindstone: {}
      minecraft:composter: {}
      minecraft:lectern: {}
      minecraft:loom: {}
      minecraft:smithing_table: {}
      minecraft:smoker: {}
      minecraft:stonecutter: {}
      minecraft:hopper: {}
      minecraft:spawner: {}
      minecraft:shulker_box: {}
      minecraft:white_shulker_box: {}
      minecraft:orange_shulker_box: {}
      minecraft:magenta_shulker_box: {}
      minecraft:light_blue_shulker_box: {}
      minecraft:yellow_shulker_box: {}
      minecraft:lime_shulker_box: {}
      minecraft:pink_shulker_box: {}
      minecraft:gray_shulker_box: {}
      minecraft:light_gray_shulker_box: {}
      minecraft:cyan_shulker_box: {}
      minecraft:purple_shulker_box: {}
      minecraft:blue_shulker_box: {}
      minecraft:brown_shulker_box: {}
      minecraft:green_shulker_box: {}
      minecraft:red_shulker_box: {}
      minecraft:black_shulker_box: {}
      minecraft:bee_nest: {}
      minecraft:beehive: {}
      minecraft:ancient_debris: {}
      minecraft:nether_gold_ore: {}
      minecraft:respawn_anchor: {}
    randomBlocks:
      minecraft:netherrack: 1
  proximity-end:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - world_the_end
    distance: 24
    useFastGazeCheck: false
    useBlockBelow: true
    hiddenBlocks:
      minecraft:chest: {}
      minecraft:ender_chest: {}
      minecraft:trapped_chest: {}
      minecraft:anvil: {}
      minecraft:crafting_table: {}
      minecraft:dispenser: {}
      minecraft:enchanting_table: {}
      minecraft:furnace: {}
      minecraft:blast_furnace: {}
      minecraft:cartography_table: {}
      minecraft:fletching_table: {}
      minecraft:grindstone: {}
      minecraft:composter: {}
      minecraft:lectern: {}
      minecraft:loom: {}
      minecraft:smithing_table: {}
      minecraft:smoker: {}
      minecraft:stonecutter: {}
      minecraft:hopper: {}
      minecraft:spawner: {}
      minecraft:shulker_box: {}
      minecraft:white_shulker_box: {}
      minecraft:orange_shulker_box: {}
      minecraft:magenta_shulker_box: {}
      minecraft:light_blue_shulker_box: {}
      minecraft:yellow_shulker_box: {}
      minecraft:lime_shulker_box: {}
      minecraft:pink_shulker_box: {}
      minecraft:gray_shulker_box: {}
      minecraft:light_gray_shulker_box: {}
      minecraft:cyan_shulker_box: {}
      minecraft:purple_shulker_box: {}
      minecraft:blue_shulker_box: {}
      minecraft:brown_shulker_box: {}
      minecraft:green_shulker_box: {}
      minecraft:red_shulker_box: {}
      minecraft:black_shulker_box: {}
      minecraft:bee_nest: {}
      minecraft:beehive: {}
    randomBlocks:
      minecraft:end_stone: 1
```
