### ISSUE TITLE
Height proximity not working

### ISSUE THREAD

**Issue by VanyaNexus** [Imprex-Development/orebfuscator#283]
### Description

Indicating the height next to the block does not work

### Reproduction Steps

I want to make sand and gravel mask into other blocks no higher than 30 in height and make this config:
```
proximity:
  proximity-overworld:
    enabled: true
    minY: -100
    maxY: 64
    worlds:
    - world
    distance: 6
    useFastGazeCheck: false
    useBlockBelow: true
    hiddenBlocks:
      minecraft:sand:
        minY: -100
        maxY: 30
```
But the sand is still hidden at any height, although of all the possible blocks in proximity, it is indicated only in this one. What could be the problem? Maybe I did something wrong?

### Expected Behaviour

Block should hide

### Server Details

paper 1.19.2

### Orebfuscator Version

5.3.3

### ProtocolLib Version

5.0.0-SNAPSHOT-b606

**Comment by NgLoader** [comment]
``minecraft:sand`` is not a valid input you just need to change it to ``sand``.
Also please checkout our [wiki](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#proximity-block-options) for configurate your hidden blocks.

You config shoudt look like this:
```yml
proximity:
  proximity-overworld:
    enabled: true
    minY: -100
    maxY: 64
    worlds:
    - world
    distance: 6
    useFastGazeCheck: false
    useBlockBelow: true
    hiddenBlocks:
      sand: {
        minY: -100
        maxY: 30
      }
```

**Comment by Ingrim4** [comment]
You have `useBlockBelow` enable which takes priority over `hiddenBlocks`. For more info on how to configure the proximity config check out our wiki [here](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#proximity-config-section).

**Comment by VanyaNexus** [comment]
I set useBlockBelow: false and still the sand is hidden above 30 coordinates and only the limit that is higher, that is, 64 blocks, works on it

**Comment by Ingrim4** [comment]
You're right just checked the code looks like I never updated it to work with the new world height since negative numbers probably will mess up the current encoding. Fix will follow soon.

P.S. the thing about `useBlockBelow` was incorrect so you can change it back to `true`

**Comment by Ingrim4** [comment]
Here is a preview with the fix implemented: https://github.com/Imprex-Development/orebfuscator/suites/12259391896/artifacts/648993747

It will take some time until we release the next version so I would recommend using that version until the then.

**Comment by VanyaNexus** [comment]
If you specify a limit higher than the main maximum, then the blocks above the main one are not hidden, even if they are redefined
```
proximity-overworld:
    enabled: true
    minY: -100
    maxY: 64
    worlds:
    - world
    distance: 6
    useFastGazeCheck: false
    useBlockBelow: true
    hiddenBlocks:
      minecraft:sand:
        minY: -100
        maxY: 40
      minecraft:gravel:
        minY: -100
        maxY: 40
      minecraft:red_sand:
        minY: -100
        maxY: 40
      minecraft:spawner:
        minY: -100
        maxY: 300
```
