### ISSUE TITLE
Ping is rising

### ISSUE THREAD

**Issue by DeriksonTM** [Imprex-Development/orebfuscator#307]
### Description

I am using Purpur 1.20.1, a plugin of the latest version

### Reproduction Steps

When logging on to the server, the ping flies up to several thousand. And when flying in observer mode or creative, the ping also flies up very much

### Expected Behaviour

I thought the ping would be stable

### Orebfuscator Dump

https://gist.github.com/DeriksonTM/c405cdd4c4cb670968805d8c946a6bdc

### Extra Details

The plugin settings are default, only the names of the worlds in which the protection should work are specified.

**Comment by DeriksonTM** [comment]
![image](https://github.com/Imprex-Development/orebfuscator/assets/92043849/d4f0b7ac-19de-47a1-bd98-d4a214447632)

**Comment by Ingrim4** [comment]
Sounds like some sort of performance issue. I would like you to run spark profiler for a couple of minutes and share the report with us so that I can see what's the core issue.

**Comment by DeriksonTM** [comment]
Ryzen9-10xCPU-24RAM-200NVMe
start flags https://pastebin.com/uQAfMjpf

Spark https://spark.lucko.me/qMDdxJJKqf


> Sounds like some sort of performance issue. I would like you to run spark profiler for a couple of minutes and share the report with us so that I can see what's the core issue.

**Comment by DeriksonTM** [comment]
Video from a lobby server with no buildings and no orebfuscator plugin - https://youtu.be/5tdgwX0UQ1w
Video from the server survival where there is a plugin orebfuscator, without this plugin ping from the top will be exactly the same as in the lobby 100-150, and when there is your plugin, ping yourself see what ping, why this happens I do not understand( - https://youtu.be/Pd_ijifLRs4

**Comment by Ingrim4** [comment]
How is the ping measured is just the ping the game tracks via keep alive packets (player list ping) or is it something else? Could you disable the cache and check if that improves it since your machine seems to be powerful enough to work without the cache.

**Comment by DeriksonTM** [comment]
![image](https://github.com/Imprex-Development/orebfuscator/assets/92043849/deddc978-899e-43bc-9e89-50e0b4c9e14e)

as I understand it is necessary to disable it, now I will try and report on the result

**Comment by DeriksonTM** [comment]
No, it didn't solve the problem(

**Comment by DeriksonTM** [comment]
And ping flies at many players at the entrance to the server, someone who lags in the blocks and die, although without the plugin all works fine and no ping flies no ping

**Comment by DeriksonTM** [comment]
How can this problem be solved in the end?

**Comment by Ingrim4** [comment]
Maybe a networking overload, you could try to reduce the randomBlocks (in overworld config) to just use stone, deepslate and bedrock to reduce packet size like so:
```yml
    randomBlocks:
      section-stone:
        minY: -5
        maxY: 2031
        blocks:
          minecraft:stone: 1
      section-deepslate:
        minY: -2032
        maxY: 5
        blocks:
          minecraft:deepslate: 1
      section-bedrock:
        minY: -64
        maxY: -60
        blocks:
          minecraft:bedrock: 1
```

**Comment by DeriksonTM** [comment]
Maybe a little better, but the ping is still there(

**Comment by DeriksonTM** [comment]
There's a definite difference, though, what you've discounted. The ping has dropped, but at times it still goes up to 800-1000.

Before your config I had this : 

what's your next recommendation?

```
version: 3
general:
  checkForUpdates: true
  updateOnBlockDamage: true
  bypassNotification: true
  ignoreSpectator: false
  updateRadius: 2
advanced:
  verbose: false
  useAsyncPacketListener: true
  maxMillisecondsPerTick: 10
  protocolLibThreads: -1
  obfuscationWorkerThreads: -1
  proximityHiderThreads: -1
cache:
  enabled: true
  baseDirectory: orebfuscator_cache
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000
  enableDiskCache: true
  maximumSize: 8192
  expireAfterAccess: 30000
  maximumTaskQueueSize: 32768
obfuscation:
  obfuscation-overworld:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
```


```
    randomBlocks:
      section-global:
        minY: -2032
        maxY: 2031
        blocks:
          minecraft:cave_air: 5
          minecraft:cobblestone: 1
          minecraft:mossy_cobblestone: 1
          minecraft:obsidian: 1
      section-stone:
        minY: -5
        maxY: 2031
        blocks:
          minecraft:stone: 15
          minecraft:diamond_ore: 20
          minecraft:emerald_ore: 10
          minecraft:gold_ore: 15
          minecraft:iron_ore: 15
          minecraft:copper_ore: 10
          minecraft:coal_ore: 10
          minecraft:lapis_ore: 10
          minecraft:redstone_ore: 10
      section-deepslate:
        minY: -2032
        maxY: 5
        blocks:
          minecraft:deepslate: 15
          minecraft:deepslate_diamond_ore: 15
          minecraft:deepslate_emerald_ore: 10
          minecraft:deepslate_gold_ore: 15
          minecraft:deepslate_iron_ore: 15
          minecraft:deepslate_copper_ore: 10
          minecraft:deepslate_coal_ore: 10
          minecraft:deepslate_lapis_ore: 10
          minecraft:deepslate_redstone_ore: 10
      section-bedrock:
        minY: -64
        maxY: -60
        blocks:
          minecraft:bedrock: 20
```

**Comment by DeriksonTM** [comment]
All server players have noticed that if you look down (under your feet) then very much drops fps.

**Comment by DeriksonTM** [comment]
![image](https://github.com/Imprex-Development/orebfuscator/assets/92043849/1ff26287-80c4-4535-880b-f5e540dd00eb)

**Comment by Ingrim4** [comment]
Can you send me your config and I will change it for you?

**Comment by DeriksonTM** [comment]
I currently have my old config back, which had high ping because a lot of people started complaining about fps, and here is my old config

```
version: 3
general:
  checkForUpdates: true
  updateOnBlockDamage: true
  bypassNotification: true
  ignoreSpectator: false
  updateRadius: 2
advanced:
  verbose: false
  useAsyncPacketListener: true
  maxMillisecondsPerTick: 10
  protocolLibThreads: -1
  obfuscationWorkerThreads: -1
  proximityHiderThreads: -1
cache:
  enabled: true
  baseDirectory: orebfuscator_cache
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000
  enableDiskCache: true
  maximumSize: 8192
  expireAfterAccess: 30000
  maximumTaskQueueSize: 32768
obfuscation:
  obfuscation-overworld:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - LiquidCloud
    - LiquidCloud_farm
    hiddenBlocks:
    - minecraft:emerald_ore
    - minecraft:deepslate_emerald_ore
    - minecraft:diamond_ore
    - minecraft:deepslate_diamond_ore
    - minecraft:gold_ore
    - minecraft:deepslate_gold_ore
    - minecraft:raw_gold_block
    - minecraft:iron_ore
    - minecraft:deepslate_iron_ore
    - minecraft:raw_iron_block
    - minecraft:coal_ore
    - minecraft:deepslate_coal_ore
    - minecraft:lapis_ore
    - minecraft:deepslate_lapis_ore
    - minecraft:redstone_ore
    - minecraft:deepslate_redstone_ore
    - minecraft:copper_ore
    - minecraft:raw_copper_block
    - minecraft:deepslate_copper_ore
    - minecraft:stone
    - minecraft:deepslate
    - minecraft:chest
    - minecraft:ender_chest
    - minecraft:trapped_chest
    - minecraft:shulker_box
    - minecraft:white_shulker_box
    - minecraft:orange_shulker_box
    - minecraft:magenta_shulker_box
    - minecraft:light_blue_shulker_box
    - minecraft:yellow_shulker_box
    - minecraft:lime_shulker_box
    - minecraft:pink_shulker_box
    - minecraft:gray_shulker_box
    - minecraft:light_gray_shulker_box
    - minecraft:cyan_shulker_box
    - minecraft:purple_shulker_box
    - minecraft:blue_shulker_box
    - minecraft:brown_shulker_box
    - minecraft:green_shulker_box
    - minecraft:red_shulker_box
    - minecraft:black_shulker_box
    - minecraft:bedrock
    randomBlocks:
      section-global:
        minY: -2032
        maxY: 2031
        blocks:
          minecraft:cave_air: 5
          minecraft:cobblestone: 1
          minecraft:mossy_cobblestone: 1
          minecraft:obsidian: 1
      section-stone:
        minY: -5
        maxY: 2031
        blocks:
          minecraft:stone: 15
          minecraft:diamond_ore: 20
          minecraft:emerald_ore: 10
          minecraft:gold_ore: 15
          minecraft:iron_ore: 15
          minecraft:copper_ore: 10
          minecraft:coal_ore: 10
          minecraft:lapis_ore: 10
          minecraft:redstone_ore: 10
      section-deepslate:
        minY: -2032
        maxY: 5
        blocks:
          minecraft:deepslate: 15
          minecraft:deepslate_diamond_ore: 15
          minecraft:deepslate_emerald_ore: 10
          minecraft:deepslate_gold_ore: 15
          minecraft:deepslate_iron_ore: 15
          minecraft:deepslate_copper_ore: 10
          minecraft:deepslate_coal_ore: 10
          minecraft:deepslate_lapis_ore: 10
          minecraft:deepslate_redstone_ore: 10
      section-bedrock:
        minY: -64
        maxY: -60
        blocks:
          minecraft:bedrock: 20
  obfuscation-nether:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - LiquidCloud_nether
    hiddenBlocks:
    - minecraft:netherrack
    - minecraft:nether_quartz_ore
    - minecraft:chest
    - minecraft:ender_chest
    - minecraft:trapped_chest
    - minecraft:shulker_box
    - minecraft:white_shulker_box
    - minecraft:orange_shulker_box
    - minecraft:magenta_shulker_box
    - minecraft:light_blue_shulker_box
    - minecraft:yellow_shulker_box
    - minecraft:lime_shulker_box
    - minecraft:pink_shulker_box
    - minecraft:gray_shulker_box
    - minecraft:light_gray_shulker_box
    - minecraft:cyan_shulker_box
    - minecraft:purple_shulker_box
    - minecraft:blue_shulker_box
    - minecraft:brown_shulker_box
    - minecraft:green_shulker_box
    - minecraft:red_shulker_box
    - minecraft:black_shulker_box
    - minecraft:ancient_debris
    - minecraft:nether_gold_ore
    - minecraft:basalt
    - minecraft:soul_sand
    - minecraft:soul_soil
    - minecraft:bedrock
    randomBlocks:
      section-global:
        minY: -2032
        maxY: 2031
        blocks:
          minecraft:netherrack: 15
          minecraft:nether_quartz_ore: 10
          minecraft:nether_gold_ore: 10
          minecraft:ancient_debris: 10
      section-bedrock-top:
        minY: 123
        maxY: 127
        blocks:
          minecraft:bedrock: 20
      section-bedrock-bottom:
        minY: 0
        maxY: 4
        blocks:
          minecraft:bedrock: 20
  obfuscation-end:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - LiquidCloud_the_end
    hiddenBlocks:
    - minecraft:chest
    - minecraft:ender_chest
    - minecraft:trapped_chest
    - minecraft:shulker_box
    - minecraft:white_shulker_box
    - minecraft:orange_shulker_box
    - minecraft:magenta_shulker_box
    - minecraft:light_blue_shulker_box
    - minecraft:yellow_shulker_box
    - minecraft:lime_shulker_box
    - minecraft:pink_shulker_box
    - minecraft:gray_shulker_box
    - minecraft:light_gray_shulker_box
    - minecraft:cyan_shulker_box
    - minecraft:purple_shulker_box
    - minecraft:blue_shulker_box
    - minecraft:brown_shulker_box
    - minecraft:green_shulker_box
    - minecraft:red_shulker_box
    - minecraft:black_shulker_box
    randomBlocks:
      section-global:
        minY: -2032
        maxY: 2031
        blocks:
          minecraft:end_stone: 1
          minecraft:end_stone_bricks: 1
          minecraft:bedrock: 1
          minecraft:obsidian: 1
          minecraft:purpur_block: 1
proximity:
  proximity-overworld:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - LiquidCloud
    - LiquidCloud_farm
    distance: 24
    useFastGazeCheck: false
    useBlockBelow: true
    hiddenBlocks:
      minecraft:mossy_cobblestone: {}
      minecraft:diamond_ore: {}
      minecraft:deepslate_diamond_ore: {}
      minecraft:emerald_ore: {}
      minecraft:deepslate_emerald_ore: {}
      minecraft:chest: {}
      minecraft:ender_chest: {}
      minecraft:trapped_chest: {}
      minecraft:anvil: {}
      minecraft:crafting_table: {}
      minecraft:dispenser: {}
      minecraft:enchanting_table: {}
      minecraft:furnace: {}
      minecraft:blast_furnace: {}
      minecraft:cartography_table: {}
      minecraft:fletching_table: {}
      minecraft:grindstone: {}
      minecraft:composter: {}
      minecraft:lectern: {}
      minecraft:loom: {}
      minecraft:smithing_table: {}
      minecraft:smoker: {}
      minecraft:stonecutter: {}
      minecraft:hopper: {}
      minecraft:spawner: {}
      minecraft:shulker_box: {}
      minecraft:white_shulker_box: {}
      minecraft:orange_shulker_box: {}
      minecraft:magenta_shulker_box: {}
      minecraft:light_blue_shulker_box: {}
      minecraft:yellow_shulker_box: {}
      minecraft:lime_shulker_box: {}
      minecraft:pink_shulker_box: {}
      minecraft:gray_shulker_box: {}
      minecraft:light_gray_shulker_box: {}
      minecraft:cyan_shulker_box: {}
      minecraft:purple_shulker_box: {}
      minecraft:blue_shulker_box: {}
      minecraft:brown_shulker_box: {}
      minecraft:green_shulker_box: {}
      minecraft:red_shulker_box: {}
      minecraft:black_shulker_box: {}
      minecraft:bee_nest: {}
      minecraft:beehive: {}
    randomBlocks:
      section-stone:
        minY: -5
        maxY: 2031
        blocks:
          minecraft:stone: 1
      section-deepslate:
        minY: -2032
        maxY: 5
        blocks:
          minecraft:deepslate: 1
  proximity-nether:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - LiquidCloud_nether
    distance: 24
    useFastGazeCheck: false
    useBlockBelow: true
    hiddenBlocks:
      minecraft:chest: {}
      minecraft:ender_chest: {}
      minecraft:trapped_chest: {}
      minecraft:anvil: {}
      minecraft:crafting_table: {}
      minecraft:dispenser: {}
      minecraft:enchanting_table: {}
      minecraft:furnace: {}
      minecraft:blast_furnace: {}
      minecraft:cartography_table: {}
      minecraft:fletching_table: {}
      minecraft:grindstone: {}
      minecraft:composter: {}
      minecraft:lectern: {}
      minecraft:loom: {}
      minecraft:smithing_table: {}
      minecraft:smoker: {}
      minecraft:stonecutter: {}
      minecraft:hopper: {}
      minecraft:spawner: {}
      minecraft:shulker_box: {}
      minecraft:white_shulker_box: {}
      minecraft:orange_shulker_box: {}
      minecraft:magenta_shulker_box: {}
      minecraft:light_blue_shulker_box: {}
      minecraft:yellow_shulker_box: {}
      minecraft:lime_shulker_box: {}
      minecraft:pink_shulker_box: {}
      minecraft:gray_shulker_box: {}
      minecraft:light_gray_shulker_box: {}
      minecraft:cyan_shulker_box: {}
      minecraft:purple_shulker_box: {}
      minecraft:blue_shulker_box: {}
      minecraft:brown_shulker_box: {}
      minecraft:green_shulker_box: {}
      minecraft:red_shulker_box: {}
      minecraft:black_shulker_box: {}
      minecraft:bee_nest: {}
      minecraft:beehive: {}
      minecraft:ancient_debris: {}
      minecraft:nether_gold_ore: {}
      minecraft:respawn_anchor: {}
    randomBlocks:
      section-global:
        minY: -2032
        maxY: 2031
        blocks:
          minecraft:netherrack: 1
  proximity-end:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - LiquidCloud_the_end
    distance: 24
    useFastGazeCheck: false
    useBlockBelow: true
    hiddenBlocks:
      minecraft:chest: {}
      minecraft:ender_chest: {}
      minecraft:trapped_chest: {}
      minecraft:anvil: {}
      minecraft:crafting_table: {}
      minecraft:dispenser: {}
      minecraft:enchanting_table: {}
      minecraft:furnace: {}
      minecraft:blast_furnace: {}
      minecraft:cartography_table: {}
      minecraft:fletching_table: {}
      minecraft:grindstone: {}
      minecraft:composter: {}
      minecraft:lectern: {}
      minecraft:loom: {}
      minecraft:smithing_table: {}
      minecraft:smoker: {}
      minecraft:stonecutter: {}
      minecraft:hopper: {}
      minecraft:spawner: {}
      minecraft:shulker_box: {}
      minecraft:white_shulker_box: {}
      minecraft:orange_shulker_box: {}
      minecraft:magenta_shulker_box: {}
      minecraft:light_blue_shulker_box: {}
      minecraft:yellow_shulker_box: {}
      minecraft:lime_shulker_box: {}
      minecraft:pink_shulker_box: {}
      minecraft:gray_shulker_box: {}
      minecraft:light_gray_shulker_box: {}
      minecraft:cyan_shulker_box: {}
      minecraft:purple_shulker_box: {}
      minecraft:blue_shulker_box: {}
      minecraft:brown_shulker_box: {}
      minecraft:green_shulker_box: {}
      minecraft:red_shulker_box: {}
      minecraft:black_shulker_box: {}
      minecraft:bee_nest: {}
      minecraft:beehive: {}
    randomBlocks:
      section-global:
        minY: -2032
        maxY: 2031
        blocks:
          minecraft:end_stone: 1

```

**Comment by Ingrim4** [comment]
Here try this please:
```yml
version: 3
general:
  checkForUpdates: true
  updateOnBlockDamage: true
  bypassNotification: true
  ignoreSpectator: false
  updateRadius: 2
advanced:
  verbose: false
  useAsyncPacketListener: true
  maxMillisecondsPerTick: 10
  protocolLibThreads: -1
  obfuscationWorkerThreads: -1
  proximityHiderThreads: -1
cache:
  enabled: true
  baseDirectory: orebfuscator_cache
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000
  enableDiskCache: true
  maximumSize: 8192
  expireAfterAccess: 30000
  maximumTaskQueueSize: 32768
obfuscation:
  obfuscation-overworld:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - LiquidCloud
    - LiquidCloud_farm
    hiddenBlocks:
    - minecraft:emerald_ore
    - minecraft:deepslate_emerald_ore
    - minecraft:diamond_ore
    - minecraft:deepslate_diamond_ore
    - minecraft:gold_ore
    - minecraft:deepslate_gold_ore
    - minecraft:raw_gold_block
    - minecraft:iron_ore
    - minecraft:deepslate_iron_ore
    - minecraft:raw_iron_block
    - minecraft:coal_ore
    - minecraft:deepslate_coal_ore
    - minecraft:lapis_ore
    - minecraft:deepslate_lapis_ore
    - minecraft:redstone_ore
    - minecraft:deepslate_redstone_ore
    - minecraft:copper_ore
    - minecraft:raw_copper_block
    - minecraft:deepslate_copper_ore
    - minecraft:stone
    - minecraft:deepslate
    - minecraft:chest
    - minecraft:ender_chest
    - minecraft:trapped_chest
    - minecraft:shulker_box
    - minecraft:white_shulker_box
    - minecraft:orange_shulker_box
    - minecraft:magenta_shulker_box
    - minecraft:light_blue_shulker_box
    - minecraft:yellow_shulker_box
    - minecraft:lime_shulker_box
    - minecraft:pink_shulker_box
    - minecraft:gray_shulker_box
    - minecraft:light_gray_shulker_box
    - minecraft:cyan_shulker_box
    - minecraft:purple_shulker_box
    - minecraft:blue_shulker_box
    - minecraft:brown_shulker_box
    - minecraft:green_shulker_box
    - minecraft:red_shulker_box
    - minecraft:black_shulker_box
    - minecraft:bedrock
    randomBlocks:
      section-stone:
        minY: -5
        maxY: 2031
        blocks:
          minecraft:stone: 1
      section-deepslate:
        minY: -2032
        maxY: 5
        blocks:
          minecraft:deepslate: 1
      section-bedrock:
        minY: -64
        maxY: -60
        blocks:
          minecraft:bedrock: 1
  obfuscation-nether:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - LiquidCloud_nether
    hiddenBlocks:
    - minecraft:netherrack
    - minecraft:nether_quartz_ore
    - minecraft:chest
    - minecraft:ender_chest
    - minecraft:trapped_chest
    - minecraft:shulker_box
    - minecraft:white_shulker_box
    - minecraft:orange_shulker_box
    - minecraft:magenta_shulker_box
    - minecraft:light_blue_shulker_box
    - minecraft:yellow_shulker_box
    - minecraft:lime_shulker_box
    - minecraft:pink_shulker_box
    - minecraft:gray_shulker_box
    - minecraft:light_gray_shulker_box
    - minecraft:cyan_shulker_box
    - minecraft:purple_shulker_box
    - minecraft:blue_shulker_box
    - minecraft:brown_shulker_box
    - minecraft:green_shulker_box
    - minecraft:red_shulker_box
    - minecraft:black_shulker_box
    - minecraft:ancient_debris
    - minecraft:nether_gold_ore
    - minecraft:basalt
    - minecraft:soul_sand
    - minecraft:soul_soil
    - minecraft:bedrock
    randomBlocks:
      section-global:
        minY: -2032
        maxY: 2031
        blocks:
          minecraft:netherrack: 15
          minecraft:nether_quartz_ore: 10
          minecraft:nether_gold_ore: 10
          minecraft:ancient_debris: 10
      section-bedrock-top:
        minY: 123
        maxY: 127
        blocks:
          minecraft:bedrock: 20
      section-bedrock-bottom:
        minY: 0
        maxY: 4
        blocks:
          minecraft:bedrock: 20
  obfuscation-end:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - LiquidCloud_the_end
    hiddenBlocks:
    - minecraft:chest
    - minecraft:ender_chest
    - minecraft:trapped_chest
    - minecraft:shulker_box
    - minecraft:white_shulker_box
    - minecraft:orange_shulker_box
    - minecraft:magenta_shulker_box
    - minecraft:light_blue_shulker_box
    - minecraft:yellow_shulker_box
    - minecraft:lime_shulker_box
    - minecraft:pink_shulker_box
    - minecraft:gray_shulker_box
    - minecraft:light_gray_shulker_box
    - minecraft:cyan_shulker_box
    - minecraft:purple_shulker_box
    - minecraft:blue_shulker_box
    - minecraft:brown_shulker_box
    - minecraft:green_shulker_box
    - minecraft:red_shulker_box
    - minecraft:black_shulker_box
    randomBlocks:
      section-global:
        minY: -2032
        maxY: 2031
        blocks:
          minecraft:end_stone: 1
          minecraft:end_stone_bricks: 1
          minecraft:bedrock: 1
          minecraft:obsidian: 1
          minecraft:purpur_block: 1
proximity:
  proximity-overworld:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - LiquidCloud
    - LiquidCloud_farm
    distance: 24
    useFastGazeCheck: false
    useBlockBelow: true
    hiddenBlocks:
      minecraft:mossy_cobblestone: {}
      minecraft:diamond_ore: {}
      minecraft:deepslate_diamond_ore: {}
      minecraft:emerald_ore: {}
      minecraft:deepslate_emerald_ore: {}
      minecraft:chest: {}
      minecraft:ender_chest: {}
      minecraft:trapped_chest: {}
      minecraft:anvil: {}
      minecraft:crafting_table: {}
      minecraft:dispenser: {}
      minecraft:enchanting_table: {}
      minecraft:furnace: {}
      minecraft:blast_furnace: {}
      minecraft:cartography_table: {}
      minecraft:fletching_table: {}
      minecraft:grindstone: {}
      minecraft:composter: {}
      minecraft:lectern: {}
      minecraft:loom: {}
      minecraft:smithing_table: {}
      minecraft:smoker: {}
      minecraft:stonecutter: {}
      minecraft:hopper: {}
      minecraft:spawner: {}
      minecraft:shulker_box: {}
      minecraft:white_shulker_box: {}
      minecraft:orange_shulker_box: {}
      minecraft:magenta_shulker_box: {}
      minecraft:light_blue_shulker_box: {}
      minecraft:yellow_shulker_box: {}
      minecraft:lime_shulker_box: {}
      minecraft:pink_shulker_box: {}
      minecraft:gray_shulker_box: {}
      minecraft:light_gray_shulker_box: {}
      minecraft:cyan_shulker_box: {}
      minecraft:purple_shulker_box: {}
      minecraft:blue_shulker_box: {}
      minecraft:brown_shulker_box: {}
      minecraft:green_shulker_box: {}
      minecraft:red_shulker_box: {}
      minecraft:black_shulker_box: {}
      minecraft:bee_nest: {}
      minecraft:beehive: {}
    randomBlocks:
      section-stone:
        minY: -5
        maxY: 2031
        blocks:
          minecraft:stone: 1
      section-deepslate:
        minY: -2032
        maxY: 5
        blocks:
          minecraft:deepslate: 1
  proximity-nether:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - LiquidCloud_nether
    distance: 24
    useFastGazeCheck: false
    useBlockBelow: true
    hiddenBlocks:
      minecraft:chest: {}
      minecraft:ender_chest: {}
      minecraft:trapped_chest: {}
      minecraft:anvil: {}
      minecraft:crafting_table: {}
      minecraft:dispenser: {}
      minecraft:enchanting_table: {}
      minecraft:furnace: {}
      minecraft:blast_furnace: {}
      minecraft:cartography_table: {}
      minecraft:fletching_table: {}
      minecraft:grindstone: {}
      minecraft:composter: {}
      minecraft:lectern: {}
      minecraft:loom: {}
      minecraft:smithing_table: {}
      minecraft:smoker: {}
      minecraft:stonecutter: {}
      minecraft:hopper: {}
      minecraft:spawner: {}
      minecraft:shulker_box: {}
      minecraft:white_shulker_box: {}
      minecraft:orange_shulker_box: {}
      minecraft:magenta_shulker_box: {}
      minecraft:light_blue_shulker_box: {}
      minecraft:yellow_shulker_box: {}
      minecraft:lime_shulker_box: {}
      minecraft:pink_shulker_box: {}
      minecraft:gray_shulker_box: {}
      minecraft:light_gray_shulker_box: {}
      minecraft:cyan_shulker_box: {}
      minecraft:purple_shulker_box: {}
      minecraft:blue_shulker_box: {}
      minecraft:brown_shulker_box: {}
      minecraft:green_shulker_box: {}
      minecraft:red_shulker_box: {}
      minecraft:black_shulker_box: {}
      minecraft:bee_nest: {}
      minecraft:beehive: {}
      minecraft:ancient_debris: {}
      minecraft:nether_gold_ore: {}
      minecraft:respawn_anchor: {}
    randomBlocks:
      section-global:
        minY: -2032
        maxY: 2031
        blocks:
          minecraft:netherrack: 1
  proximity-end:
    enabled: true
    minY: -2032
    maxY: 2031
    worlds:
    - LiquidCloud_the_end
    distance: 24
    useFastGazeCheck: false
    useBlockBelow: true
    hiddenBlocks:
      minecraft:chest: {}
      minecraft:ender_chest: {}
      minecraft:trapped_chest: {}
      minecraft:anvil: {}
      minecraft:crafting_table: {}
      minecraft:dispenser: {}
      minecraft:enchanting_table: {}
      minecraft:furnace: {}
      minecraft:blast_furnace: {}
      minecraft:cartography_table: {}
      minecraft:fletching_table: {}
      minecraft:grindstone: {}
      minecraft:composter: {}
      minecraft:lectern: {}
      minecraft:loom: {}
      minecraft:smithing_table: {}
      minecraft:smoker: {}
      minecraft:stonecutter: {}
      minecraft:hopper: {}
      minecraft:spawner: {}
      minecraft:shulker_box: {}
      minecraft:white_shulker_box: {}
      minecraft:orange_shulker_box: {}
      minecraft:magenta_shulker_box: {}
      minecraft:light_blue_shulker_box: {}
      minecraft:yellow_shulker_box: {}
      minecraft:lime_shulker_box: {}
      minecraft:pink_shulker_box: {}
      minecraft:gray_shulker_box: {}
      minecraft:light_gray_shulker_box: {}
      minecraft:cyan_shulker_box: {}
      minecraft:purple_shulker_box: {}
      minecraft:blue_shulker_box: {}
      minecraft:brown_shulker_box: {}
      minecraft:green_shulker_box: {}
      minecraft:red_shulker_box: {}
      minecraft:black_shulker_box: {}
      minecraft:bee_nest: {}
      minecraft:beehive: {}
    randomBlocks:
      section-global:
        minY: -2032
        maxY: 2031
        blocks:
          minecraft:end_stone: 1
```
